import { useMemo, useState } from "react";
import Pressable from "../components/Pressable";
import { Collapse, DisclosureButton } from "../components/Collapse";
import { SectionTitle } from "../components/primitives";
import { C, DIVIDER, DIVIDER_TOP, R, T } from "../tokens";
import {
  clearAllPanels,
  panelFields,
  parsePaste,
  pctToM,
  readPanel,
  savePanel,
  savedIds,
} from "../data/panel";
import { SESSIONS, pick } from "../data/sessions";
import { useLang } from "../i18n";

/**
 * The plate, as typed in.
 *
 * This is the screen the product did not have. Every number the app shows was
 * generated by a seeded walk in body.js; there was no way to hand it a real
 * result. Now there is, and the point of the screen is the round trip: change
 * ALT here and the body row, the deviation in the liver sheet, the health
 * score, the mind index that marker feeds and the liver trend in signals all
 * move together, because they were always computed — they just had nothing
 * real to compute from.
 *
 * Paste is the primary path. A lab hands over a column of name and value, and
 * nobody is typing a hundred and five fields twice.
 *
 * Methylation shows both units side by side. The panel reports beta and the
 * models run on M, and putting the pair on screen is the cheapest way to make
 * that rule visible to whoever is entering the plate.
 */
export default function PanelEntry({ sel, onChanged }) {
  const { t, lang } = useLang();
  const groups = useMemo(() => panelFields(), []);
  const session = SESSIONS[sel];
  const round = session.roundIndex;

  const [draft, setDraft] = useState(() => readPanel(round));
  const [paste, setPaste] = useState("");
  const [note, setNote] = useState(null);
  const [openGroup, setOpenGroup] = useState(groups[0]?.key ?? null);
  const overridden = useMemo(() => savedIds(round), [round, note]);

  const dirty = useMemo(() => {
    const base = readPanel(round);
    return Object.keys(draft).filter(
      (id) => Number(draft[id]) !== Number(base[id]),
    );
  }, [draft, round, note]);

  const commit = () => {
    const record = {};
    dirty.forEach((id) => {
      const v = Number(draft[id]);
      if (Number.isFinite(v)) record[id] = v;
    });
    const n = savePanel(round, record);
    setNote({ kind: "saved", n });
    onChanged?.();
  };

  const applyPaste = () => {
    const { record, unmatched } = parsePaste(paste, t);
    setDraft((d) => ({ ...d, ...record }));
    setNote({ kind: "pasted", n: Object.keys(record).length, unmatched });
  };

  const resetAll = () => {
    clearAllPanels();
    setNote({ kind: "cleared" });
    onChanged?.();
    // Values already written into the series stay until reload; say so rather
    // than pretend the reset was total.
  };

  return (
    <div>
      <div style={{ ...T.caption, color: C.faint, textWrap: "pretty" }}>
        {t("panel.intro", {
          round: session.round,
          date: pick(session.fullDate, lang),
        })}
      </div>

      {/* Paste first: it is how a plate actually arrives. */}
      <SectionTitle>{t("panel.paste")}</SectionTitle>
      <textarea
        value={paste}
        onChange={(e) => setPaste(e.target.value)}
        placeholder={t("panel.pasteHint")}
        rows={4}
        style={{
          width: "100%",
          boxSizing: "border-box",
          ...T.num,
          fontSize: 12,
          color: C.ink,
          background: C.surface,
          border: "none",
          borderRadius: R.card,
          padding: "12px 13px",
          resize: "vertical",
          outline: "none",
          boxShadow: `inset 0 0 0 1px ${C.hairline}`,
        }}
      />
      <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
        <Button onClick={applyPaste} disabled={!paste.trim()}>
          {t("panel.applyPaste")}
        </Button>
        <Button onClick={resetAll} subtle>
          {t("panel.reset")}
        </Button>
      </div>

      {note && (
        <div
          style={{
            ...T.caption,
            color: note.unmatched?.length ? C.watch : C.body,
            marginTop: 10,
            textWrap: "pretty",
          }}
        >
          {note.kind === "saved" && t("panel.saved", { n: note.n })}
          {note.kind === "cleared" && t("panel.clearedNote")}
          {note.kind === "pasted" &&
            (note.unmatched.length
              ? t("panel.pastedSome", {
                  n: note.n,
                  bad: note.unmatched.slice(0, 3).join(" / "),
                })
              : t("panel.pastedAll", { n: note.n }))}
        </div>
      )}

      {/* The full plate, grouped the way the panels are grouped. */}
      <SectionTitle
        value={String(groups.reduce((n, g) => n + g.fields.length, 0))}
      >
        {t("panel.allFields")}
      </SectionTitle>
      {groups.map((g) => (
        <div key={g.key} style={{ marginBottom: 4 }}>
          <DisclosureButton
            open={openGroup === g.key}
            onClick={() => setOpenGroup(openGroup === g.key ? null : g.key)}
            label={t(g.nameKey)}
            hint={t("panel.nFields", { n: g.fields.length })}
          />
          <Collapse open={openGroup === g.key}>
            <div style={{ padding: "6px 0 14px" }}>
              {g.fields.map((f) => (
                <Row
                  key={f.id}
                  field={f}
                  value={draft[f.id]}
                  overridden={overridden.has(f.id)}
                  changed={dirty.includes(f.id)}
                  onChange={(v) => setDraft((d) => ({ ...d, [f.id]: v }))}
                  t={t}
                />
              ))}
            </div>
          </Collapse>
        </div>
      ))}

      <div
        style={{
          position: "sticky",
          bottom: 0,
          background: C.bg,
          paddingTop: 12,
          marginTop: 12,
          boxShadow: DIVIDER_TOP,
        }}
      >
        <Pressable
          as="button"
          type="button"
          onClick={commit}
          disabled={!dirty.length}
          pressScale={0.98}
          style={{
            width: "100%",
            padding: "14px 15px",
            borderRadius: R.card,
            border: "none",
            cursor: dirty.length ? "pointer" : "default",
            background: dirty.length ? C.accent : C.chipIdle,
            color: dirty.length ? C.onAccent : C.faintest,
            ...T.title3,
          }}
        >
          {dirty.length
            ? t("panel.save", { n: dirty.length })
            : t("panel.noChanges")}
        </Pressable>
      </div>
    </div>
  );
}

function Row({ field, value, overridden, changed, onChange, t }) {
  const isBeta = field.isBeta;
  const num = Number(value);
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 10,
        padding: "8px 2px",
        boxShadow: DIVIDER,
      }}
    >
      <span style={{ flex: 1, minWidth: 0 }}>
        <span style={{ ...T.caption, color: C.ink, display: "block" }}>
          {field.plainKey ? t(field.plainKey) : field.label}
        </span>
        <span
          style={{
            ...T.micro,
            color: C.faintest,
            display: "block",
            marginTop: 1,
          }}
        >
          {field.label}
          {field.ref != null &&
            ` · ${t(field.dir === "low" ? "body.referenceMin" : "body.reference", { v: field.ref })}`}
          {/* The logit, next to the value it comes from. */}
          {isBeta && Number.isFinite(num) && ` · M ${pctToM(num).toFixed(2)}`}
        </span>
      </span>
      <input
        type="number"
        inputMode="decimal"
        step="any"
        value={value ?? ""}
        onChange={(e) => onChange(e.target.value)}
        style={{
          width: 84,
          flex: "none",
          textAlign: "right",
          ...T.num,
          fontSize: 13,
          color: C.ink,
          background: changed ? C.watchTint : C.surface,
          border: "none",
          borderRadius: R.control,
          padding: "8px 9px",
          outline: "none",
          boxShadow: overridden
            ? `inset 0 0 0 1px ${C.hairlineStrong}`
            : `inset 0 0 0 1px ${C.hairline}`,
        }}
      />
      <span
        style={{
          ...T.micro,
          color: C.faintest,
          width: 40,
          flex: "none",
        }}
      >
        {field.unit || ""}
      </span>
    </div>
  );
}

function Button({ children, onClick, disabled, subtle }) {
  return (
    <Pressable
      as="button"
      type="button"
      onClick={onClick}
      disabled={disabled}
      pressScale={disabled ? 1 : 0.97}
      style={{
        ...T.caption,
        padding: "9px 13px",
        borderRadius: R.control,
        border: "none",
        cursor: disabled ? "default" : "pointer",
        background: subtle ? "transparent" : C.surfaceSunken,
        color: disabled ? C.disabled : subtle ? C.faint : C.ink,
        boxShadow: subtle ? `inset 0 0 0 1px ${C.hairline}` : "none",
      }}
    >
      {children}
    </Pressable>
  );
}
